export const planets = [
  { name: 'Littlehip Hawthorn' },
  { name: 'Monkshoodvine' },
  { name: 'Buckthorn Bully' },
  { name: "Ram's Head Lady's Slipper" },
  { name: 'Zelometeorium Moss' },
  { name: 'Heather Leaf-flower' },
  { name: 'Stiff Marsh Bedstraw' },
  { name: 'Pelekunu Trail Yellow Loosestrife' },
  { name: 'Birch' },
  { name: 'Compact White Sage' },
  { name: 'Sickletop Lousewort' },
  { name: 'Coastal Sage Scrub Oak' },
  { name: "Pilo Kea Lau Li'i" },
  { name: 'Molokai Cyrtandra' },
  { name: 'Allicoche Hedgehog Cactus' },
  { name: 'Giant Swordfern' },
  { name: 'Fragrant Maidenhair' },
  { name: 'Manchurian Wildrice' },
  { name: 'Saddle Mountain Saxifrage' },
  { name: 'Threeleaf Indigo' },
  { name: 'Spiked Bur Grass' },
  { name: 'Blue Cohosh' },
  { name: 'Largeleaf Sphagnum' },
  { name: 'Southern Suncup' },
  { name: 'Common Goldenstar' },
  { name: 'Seagrass' },
  { name: 'Wingleaf Soapberry' },
  { name: 'Hillside Vervain' },
  { name: 'Boxleaf Stopper' },
  { name: 'Campsis' },
  { name: "Parry's Jepsonia" },
  { name: 'Nevada Podistera' },
  { name: 'Glandular Willowherb' },
  { name: "Wright's Blue Eyed Mary" },
  { name: 'Gingermint' },
  { name: "Wright's Goldenrod" },
  { name: 'American Thorow Wax' },
  { name: 'Thrombium Lichen' },
  { name: "Schaerer's Psorotichia Lichen" },
  { name: 'Sonoran Panicgrass' },
  { name: "Bessey's Locoweed" },
  { name: 'Chisos Mountain Century Plant' },
  { name: 'Roving Pricklypear' },
  { name: 'Greater Water Dock' },
  { name: 'Cudweed' },
  { name: 'Purple Sand Verbena' },
  { name: 'Pine Barren Fluffgrass' },
  { name: 'Goatweed' },
  { name: 'Conejo Dudleya' },
  { name: 'Purple Bluestem' },
  { name: 'Dalbergia' },
  { name: 'False Amaranth' },
  { name: 'Bahiagrass' },
  { name: 'Shakeshake' },
  { name: 'Oconee Bells' },
  { name: 'Golden Colicroot' },
  { name: 'Chaffbush' },
  { name: 'Sierra Valley Mousetail' },
  { name: 'Hairy Yellow Vetch' },
  { name: 'Bog Clermontia' },
  { name: 'Scrub Plum' },
  { name: "Meyen's Twinsorus Fern" },
  { name: 'Tropical Nutrush' },
  { name: 'Meadow Alexanders' },
  { name: "Kalm's Hawkweed" },
  { name: 'Frogwood' },
  { name: 'Largeleaf Waterleaf' },
  { name: 'Pacific Reindeer Lichen' },
  { name: 'Neolloydia' },
  { name: 'Spectacular Flatsedge' },
  { name: 'Yucatan Camphorweed' },
  { name: 'Basora' },
  { name: 'Orange Lichen' },
  { name: "Sipe's Kidney Lichen" },
  { name: 'Conanicut Island Blackberry' },
  { name: 'Glandular Maiden Fern' },
  { name: 'Kaala Phyllostegia' },
  { name: 'Nutrush' },
  { name: 'Mongolian Pride-of-rochester' },
  { name: 'Sand Live Oak' },
  { name: 'Amazon Waterlily' },
  { name: 'Assyrian Plum' },
  { name: "Child's Blue Eyed Mary" },
  { name: "Hickman's Knotweed" },
  { name: 'Eastern Featherbells' },
  { name: 'Bulletwood' },
  { name: 'Calabar Bean' },
  { name: 'Marubio Oscuro' },
  { name: 'Modoc Hawksbeard' },
  { name: 'Northwest Sandbar Willow' },
  { name: 'Circumpolar Sedge' },
  { name: "Queen's-wreath" },
  { name: "Holm's Ragwort" },
  { name: 'Stout Smartweed' },
  { name: "Weber's Draba" },
  { name: "Piper's Golden Buckwheat" },
  { name: 'Manilkara' },
  { name: "Berlandier's Hedgehog Cactus" },
  { name: "Drummond's Nailwort" },
  { name: "Wright's Milkvetch" }
]
